services:
  mage:
    image: mageai/mageai:latest
    container_name: ${MAGE_CONTAINER_NAME}
    command: mage start ${PROJECT_NAME}
    env_file:
      - dw.env
    ports:
      - "6795:6789"
    volumes:
      - .:/home/src/
    restart: on-failure:5
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    restart: on-failure
    container_name: ${DW_CONTAINER_NAME}
    env_file:
      - dw.env
    ports:
      - "${DW_HOST_PORT}:${DW_CONTAINER_PORT}"
    expose:
      - ${DW_CONTAINER_PORT}
    volumes:
      - dz-job-pipeline-postgres-data-17:/var/lib/postgresql/data
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh

  metabase:
    image: metabase/metabase:latest
    container_name: ${METABASE_APP_CONTAINER_NAME}
    volumes:
      - /dev/urandom:/dev/random:ro
    env_file:
      - metabase.env
    ports:
      - ${MB_APP_HOST_PORT}:${MB_APP_CONTAINER_PORT}
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      - metabase-db
  
  metabase-db:
    image: postgres:14
    container_name: ${METABASE_DB_CONTAINER_NAME}
    env_file:
      - metabase.env
    expose:
      - ${MB_DB_PORT}
    volumes:
      - dz-job-pipeline-metabase-data:/var/lib/postgresql/data


volumes:
  dz-job-pipeline-postgres-data-17:
  dz-job-pipeline-metabase-data:
