triggers:
- description: null
  envs: []
  last_enabled_at: 2025-05-19 18:10:08.837876
  name: daily trigger
  pipeline_uuid: dz_jobs_pipeline
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    allow_blocks_to_fail: true
  sla: null
  start_time: 2025-05-19 01:00:00
  status: active
  token: aaff5bb9ffdb460e9215b7497d42fd55
  variables:
    NUM_LISTINGS: 100
    PAGE: 1
    backfill: false
